// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Puchero.Api.Infrastructure;

#nullable disable

namespace Puchero.Api.Migrations
{
    [DbContext(typeof(PucheroDbContext))]
    partial class PucheroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlanSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_slot_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_attendances_user_id");

                    b.HasIndex("PlanSlotId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_plan_slot_id_user_id");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_meals_family_id");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.PlanSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("service");

                    b.Property<Guid>("WeekPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("week_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_plan_slots");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_plan_slots_meal_id");

                    b.HasIndex("WeekPlanId", "DayOfWeek", "Service")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_slots_week_plan_id_day_of_week_service");

                    b.ToTable("plan_slots", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("integer")
                        .HasColumnName("color_index");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_users_family_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.WeekPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id")
                        .HasName("pk_week_plans");

                    b.HasIndex("FamilyId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ix_week_plans_family_id_week_start");

                    b.ToTable("week_plans", (string)null);
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Puchero.Api.Domain.Entities.PlanSlot", "PlanSlot")
                        .WithMany("Absences")
                        .HasForeignKey("PlanSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_plan_slots_plan_slot_id");

                    b.HasOne("Puchero.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_users_user_id");

                    b.Navigation("PlanSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Meal", b =>
                {
                    b.HasOne("Puchero.Api.Domain.Entities.Family", "Family")
                        .WithMany("Meals")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meals_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.PlanSlot", b =>
                {
                    b.HasOne("Puchero.Api.Domain.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plan_slots_meals_meal_id");

                    b.HasOne("Puchero.Api.Domain.Entities.WeekPlan", "WeekPlan")
                        .WithMany("Slots")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_slots_week_plans_week_plan_id");

                    b.Navigation("Meal");

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("Puchero.Api.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.WeekPlan", b =>
                {
                    b.HasOne("Puchero.Api.Domain.Entities.Family", "Family")
                        .WithMany("WeekPlans")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_week_plans_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.Family", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Members");

                    b.Navigation("WeekPlans");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.PlanSlot", b =>
                {
                    b.Navigation("Absences");
                });

            modelBuilder.Entity("Puchero.Api.Domain.Entities.WeekPlan", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
